In [2]:
# array properties
import numpy as np

In [9]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(arr)
print(arr.shape) # dimensioins = m X n
print(arr.size) # total element
print(arr.dtype) # data type
print(arr.ndim) # number of dimension

# cnage data type
arr_float = arr.astype(np.float64)
print(arr_float, arr_float.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
12
int64
2
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]] float64
